<?php
/**
 * Config file for PHPFormMaker 
 * 
 * DO NOT EDIT THIS FILE!
 * 
 * Create a new file of this and call it config.php
 */

// Database Information.
$servername = 'localhost'; // enter the proper servername here.
$dbname = 'PHPFormMaker'; // choose your database name.
$username = 'root'; // username for the database.
$password = 'root'; // password to enter the database.
$table = 'PhpForm'; // table to put the information

// SMTP Server Information.
$emailServer  = 'mail.server.com';  // enter your mail server name here.
$emailUser = 'username'; // enter your mail username here. 
$emailPassword = 'password'; // enter your password here.
$emailPort = 587; //verify the port your SMTP uses
